apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: rdma-device-daemonset
spec:
  template:
    metadata:
      # This annotation is deprecated, kept here for backward compatibility
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: rdma-device-ds
    spec:
      nodeSelector:
        node-role.kubernetes.io/jarvice-compute: ""
      tolerations:
        # This toleration is deprecated, kept here for backward compatibility
        # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
        - key: CriticalAddonsOnly
          operator: Exists
        - key: jarvice.com/rdma
          operator: Exists
          effect: NoSchedule
        - key:  node-role.kubernetes.io/jarvice-compute
          operator: Exists
          effect: NoSchedule
      # Mark this pod as a critical add-on; when enabled, the critical add-on
      # scheduler reserves resources for critical add-on pods so that they can
      # be rescheduled after a failure.
      # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
      # not supported yet...
      #priorityClassName: "system-node-critical"
      containers:
        - image: jarvice/k8s-rdma-device:1.0.0
          # pull policy at Always useful for testing
          imagePullPolicy: Always
          name: jarvice-rdma-device-plugin
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: devinfiniband
              mountPath: /dev/infiniband
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: devinfiniband
          hostPath:
            path: /dev/infiniband